/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import com.mysql.jdbc.Connection;
import conexionSQL.ConexionSQL;
import static formulario.transporte.btnActualizarConductor;
import static formulario.transporte.btnEliminarConductor;
import static formulario.transporte.btnNuevoConductor;
import static formulario.transporte.tablaConductor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JHON.CHAVEZ
 */
public class NewConductor extends javax.swing.JFrame {
    ConexionSQL cc = new ConexionSQL();
    Connection con =cc.Conexion();
    int posx,posy;

    /**
     * Creates new form NewConductor
     */
    public NewConductor() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarAuto();
        
        elemtns_trasnparent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCrearUsuario = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        txtDocumento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        FechaNacimientoCond = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        numeroAuto = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 480));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Documento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 65, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 45, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 45, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Licencia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 190, 48, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha Nacimiento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 101, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 250, 49, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dirección");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 54, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 310, 39, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Auto");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 340, 26, 16);

        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearUsuario);
        btnCrearUsuario.setBounds(260, 390, 50, 50);

        btnActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarUsuario);
        btnActualizarUsuario.setBounds(340, 390, 50, 50);

        txtDocumento.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDocumento);
        txtDocumento.setBounds(160, 100, 236, 24);

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNombre);
        txtNombre.setBounds(160, 130, 236, 24);

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtApellido);
        txtApellido.setBounds(160, 160, 236, 24);

        txtLicencia.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLicencia);
        txtLicencia.setBounds(160, 190, 236, 24);

        FechaNacimientoCond.setBackground(new java.awt.Color(255, 255, 255));
        FechaNacimientoCond.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(FechaNacimientoCond);
        FechaNacimientoCond.setBounds(160, 220, 236, 20);

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(160, 250, 236, 24);

        txtDireccion.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(160, 280, 236, 24);

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(160, 310, 236, 24);

        numeroAuto.setBackground(new java.awt.Color(255, 255, 255));
        numeroAuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(numeroAuto);
        numeroAuto.setBounds(160, 340, 236, 26);

        jLabel10.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Editar Usuario");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 30, 180, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/4308065-32.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 0, 30, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo8.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 480, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
        actualizarConductor();
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        insertarConductor();
        //limpiarCajas();
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        //System.exit(0);
        dispose();
        mostrarConductores();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int xp=evt.getXOnScreen() -posx;
        int yp=evt.getYOnScreen() -posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        posx=evt.getX();      
        posy=evt.getY();
    }//GEN-LAST:event_formMousePressed

    public void elemtns_trasnparent(){
        btnCrearUsuario.setContentAreaFilled(false);
        btnCrearUsuario.setBorderPainted(false);
        
        btnActualizarUsuario.setContentAreaFilled(false);
        btnActualizarUsuario.setBorderPainted(false);
    }
    
        public void mostrarAuto(){
        String registros = "";
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        String SQL = "SELECT * FROM automovil";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                //registros[0]=rs.getString("id_auto");
                registros=rs.getString("placa");
                //registros[2]=rs.getString("marca");
                //registros[3]=rs.getString("modelo");
                //registros[4]=rs.getString("color");
                
                modelo.addElement(registros);
            }
            numeroAuto.setModel(modelo);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
        
    }
        
    public int getidAuto(String placa){
        String SQL = "SELECT * FROM automovil where placa = '"+placa+"'";
        int id = 0;
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                
                id=rs.getInt("id_auto");

            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
        return id;
    }
                                              

    
    public void insertarConductor(){
        try {
            String SQL = "insert into conductor (documento, nombre, apellido, licencia, fecha_nacimiento, telefono, direccion, correo, fk_idauto)"
                    + " values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, txtDocumento.getText());
            pst.setString(2, txtNombre.getText());
            pst.setString(3, txtApellido.getText());
            pst.setString(4, txtLicencia.getText());
            pst.setString(5, ((JTextField)FechaNacimientoCond.getDateEditor().getUiComponent()).getText());
            pst.setString(6, txtTelefono.getText());
            pst.setString(7, txtDireccion.getText());
            pst.setString(8, txtCorreo.getText());
            
            String placa = numeroAuto.getSelectedItem().toString();
            int id=getidAuto(placa);
            pst.setString(9, String.valueOf(id));
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro exitoso");
            mostrarConductores();
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Registro"+ e.getMessage());
        }
    }
    
    public void mostrarConductores(){
        String[] titulos = {"Documento", "Nombre","Apellido", "Licencia","Nacimiento","Telefono","Direccion","Correo","Auto"};
        String [] registros = new String[9];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT *,placa FROM conductor join automovil on fk_idauto = id_auto";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0]=rs.getString("documento");
                registros[1]=rs.getString("nombre");
                registros[2]=rs.getString("apellido");
                registros[3]=rs.getString("licencia");
                registros[4]=rs.getString("fecha_nacimiento");
                registros[5]=rs.getString("telefono");
                registros[6]=rs.getString("direccion");
                registros[7]=rs.getString("correo");
                registros[8]=rs.getString("placa");
                modelo.addRow(registros);
            }
            tablaConductor.setModel(modelo);
            btnNuevoConductor.setEnabled(true);
            btnActualizarConductor.setEnabled(false);
            btnEliminarConductor.setEnabled(false);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
    }
    
    public  void limpiarCajas(){
        txtDocumento.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtLicencia.setText("");
        //FechaNacimientoCond.actionPerformed();
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        numeroAuto.setAction((Action) numeroAuto);
        
    }
    
    public void actualizarConductor(){
        
        try {
            String SQL = "update conductor set nombre=?, apellido=?, licencia=?, fecha_nacimiento=?, telefono=?, direccion=?, correo=?, fk_idauto=? where documento=?";
            
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, txtNombre.getText());
            pst.setString(2, txtApellido.getText());
            pst.setString(3, txtLicencia.getText());
            pst.setString(4, ((JTextField)FechaNacimientoCond.getDateEditor().getUiComponent()).getText());
            pst.setString(5, txtTelefono.getText());
            pst.setString(6, txtDireccion.getText());
            pst.setString(7, txtCorreo.getText());
            
            String placa = numeroAuto.getSelectedItem().toString();
            int id=getidAuto(placa);
            pst.setString(8, String.valueOf(id));
            
            pst.setString(9, txtDocumento.getText());
             pst.execute();
            JOptionPane.showMessageDialog(null, "Registro actualizado");
            this.dispose();
            mostrarConductores();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de actualizacion "+ e.getMessage());
        }
        
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser FechaNacimientoCond;
    public static javax.swing.JButton btnActualizarUsuario;
    public static javax.swing.JButton btnCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JComboBox<String> numeroAuto;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtCorreo;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtDocumento;
    public static javax.swing.JTextField txtLicencia;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
