/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import static app.chatInterno.tablaCampana;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JHON.CHAVEZ
 */
public class addCampana extends javax.swing.JFrame {

    
    int posx, posy;
    Db cc = new Db();
    Connection con = (Connection) cc.connect();
    

    Calendar calendario = Calendar.getInstance();
    public static  int idCampana;

    /**
     * Creates new form addCampana
     */
    public addCampana() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        //mostrarCampana();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreCampana = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInsertarC = new javax.swing.JButton();
        cbxEstadoC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnActualizarC = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 450));
        setUndecorated(true);
        getContentPane().setLayout(null);

        txtNombreCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCampanaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreCampana);
        txtNombreCampana.setBounds(160, 97, 236, 24);

        jLabel1.setText("Nombre Campaña");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 101, 102, 16);

        jLabel4.setText("Estado");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 159, 39, 16);

        btnInsertarC.setText("Insertar");
        btnInsertarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertarC);
        btnInsertarC.setBounds(205, 304, 86, 32);

        cbxEstadoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        cbxEstadoC.setSelectedIndex(0);
        getContentPane().add(cbxEstadoC);
        cbxEstadoC.setBounds(160, 154, 111, 26);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(396, 0, 12, 24);

        btnActualizarC.setText("Actualizar");
        btnActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarC);
        btnActualizarC.setBounds(309, 304, 87, 32);

        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMouseDragged(evt);
            }
        });
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
        });
        getContentPane().add(fondo);
        fondo.setBounds(0, -4, 420, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCActionPerformed
        nuevaCampana();
    }//GEN-LAST:event_btnInsertarCActionPerformed

    private void btnActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCActionPerformed
        actualizarCampana();
        
    }//GEN-LAST:event_btnActualizarCActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        
    }//GEN-LAST:event_jLabel2MouseDragged

    private void fondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseDragged
        int xp = evt.getXOnScreen() - posx;
        int yp = evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_fondoMouseDragged

    private void fondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fondoMouseClicked

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_fondoMousePressed

    private void txtNombreCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCampanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCampanaActionPerformed

    public void mostrarCampana(){
        String[] titulos = {"ID", "Nombre","Creador", "Fecha","estado"};
        String [] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT * FROM campana";
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0]=rs.getString("idcampana");
                registros[1]=rs.getString("nombreCampana");
                registros[2]=rs.getString("creadorCampana");
                registros[3]=rs.getString("fechaCreacionCam");
                //registros[4]=rs.getString("estadoCamp");
                int estado = rs.getInt("estadoCamp");
                if(estado == 0) {
                    registros[4] = "Inactivo";
                }else if (estado == 1) {
                    registros[4] = "Activo";
                }
                modelo.addRow(registros);
            }
            tablaCampana.setModel(modelo);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error de datos"+ e.getMessage());
        }
    }
    
   
    
    public void nuevaCampana() {
        try {
            String SQL = "insert into campana (nombreCampana, creadorCampana, fechaCreacionCam, estadoCamp) values (?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, txtNombreCampana.getText());
            
            LoginForm lg = new LoginForm();
            pst.setString(2, lg.dt);

            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Date date = new Date();
            pst.setString(3, (dateFormat.format(date)));

            int seleccionado = cbxEstadoC.getSelectedIndex();
            pst.setString(4, Integer.toString(seleccionado));

            pst.execute();

            JOptionPane.showMessageDialog(null, "Registro exitoso");
            mostrarCampana();
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Registro" + e.getMessage());
        }
    }

    
     public void actualizarCampana(){
        
        try {
            String SQL = "update campana set nombreCampana=?, estadoCamp=? where idcampana=?";
            PreparedStatement pst = con.prepareStatement(SQL);
            
            pst.setString(1, txtNombreCampana.getText());
            
//            int seleccionado = cbxEstadoC.getSelectedIndex();
//            pst.setString(2, Integer.toString(seleccionado));
            
            int estado = cbxEstadoC.getSelectedIndex();
            pst.setInt(2, estado);
            
            pst.setInt(3, this.idCampana);
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Registro actualizado");
            this.dispose();
            mostrarCampana();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de actualizacion "+ e.getMessage());
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCampana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCampana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCampana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCampana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new addCampana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnActualizarC;
    public static javax.swing.JButton btnInsertarC;
    public static javax.swing.JComboBox<String> cbxEstadoC;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField txtNombreCampana;
    // End of variables declaration//GEN-END:variables
}
